project:
  name: nyc_taxi_platform

storage:
  bucket_name: nyc-traffic-spark-2026

layers:
  bronze: raw
  silver: silver
  gold: gold

datasets:
  yellow_trip:
    source_name: yellow_tripdata
    start_year: 2015
    start_month: 1
    end_year: 2024
    end_month: 8

  green_trip:
    source_name: green_tripdata
    start_year: 2015
    start_month: 1
